name: Trigger auto deployment for corrida-cachorro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/corrida-cachorro-AutoDeployTrigger-a9e79a55-2223-4ce0-9dc0-e79a25b0ccef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CORRIDACACHORRO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CORRIDACACHORRO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CORRIDACACHORRO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CORRIDACACHORRO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CORRIDACACHORRO_REGISTRY_PASSWORD }}
          containerAppName: corrida-cachorro
          resourceGroup: academia-back-end
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


